# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-01 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltype',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
