# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensible', '0002_auto_20161101_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='extensible.ModelType')),
            ],
        ),
        migrations.AddField(
            model_name='modeltype',
            name='primary_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extensible.ModelSubType'),
        ),
    ]
